参考：

numpy.take_along_axis: https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html#numpy-take-along-axis

numpy.put_along_axis: https://numpy.org/doc/stable/reference/generated/numpy.put_along_axis.html#numpy-put-along-axis

In [1]:
import numpy as np
np.random.seed(0)

In [2]:
a = np.random.randint(10, size=24).reshape(6, 4)
a

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

筛选出每一行中最大的 2 个数，将它们的索引放到每一行的最右边的 2 个位置

注意需要将 `kth` 设为 3，而不是 2。仔细检查下面的 partition_index 中最后一行就可以发现，当将 `kth` 设为 3 时，最大的两个数被放到了最右边，而 `8` 虽然是第三大的数，但它却被放到了最左边，说明它被分到了较小的那一堆中，并且每堆的内部是不需要排序的。

In [3]:
partition_index = np.argpartition(a, kth=3)
partition_index

array([[1, 3, 2, 0],
       [2, 3, 0, 1],
       [0, 1, 3, 2],
       [2, 3, 0, 1],
       [3, 0, 1, 2],
       [2, 0, 1, 3]])

将原矩阵每一行中最大的 2 个数保留，其他的数设为 0

In [4]:
desired_index = partition_index[:, :-2]
desired_index

array([[1, 3],
       [2, 3],
       [0, 1],
       [2, 3],
       [3, 0],
       [2, 0]])

In [5]:
a

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

用 `np.take_along_axis()` 取出某个索引的值，可以发现这些值就是每一行中较小的数

In [6]:
np.take_along_axis(a, desired_index, axis=1)

array([[0, 3],
       [3, 5],
       [2, 4],
       [1, 6],
       [1, 7],
       [8, 5]])

但我们需要将这些较小的值全部赋值为 0，可以用 `np.put_along_axis()`

In [7]:
np.put_along_axis(a, desired_index, values=0, axis=1)

In [8]:
a

array([[5, 0, 3, 0],
       [7, 9, 0, 0],
       [0, 0, 7, 6],
       [8, 8, 0, 0],
       [0, 7, 8, 0],
       [0, 9, 0, 9]])